exclude_paths:
    - docs/**/*
    - tests/**/*
    - migrations/**/*
    - rbac/migrations/**/*
    - models/invitation/migrations/**/*
    - models/log/migrations/**/*
    
ratings:
    paths:
        - rbac/**
        - forms/**
        - security/**
        - widgets/**
        - Profile.php
        - SimpleProfile.php
        - User.php
        
engines:
    phpmd:
        enabled: true
    phpcodesniffer:
        enabled: true
