<?php

/**
 *  _   __ __ _____ _____ ___  ____  _____
 * | | / // // ___//_  _//   ||  __||_   _|
 * | |/ // /(__  )  / / / /| || |     | |
 * |___//_//____/  /_/ /_/ |_||_|     |_|
 * @link https://vistart.me/
 * @copyright Copyright (c) 2016 - 2017 vistart
 * @license https://vistart.me/license/
 */

namespace rhosocial\user\tests\models\invitation;

use rhosocial\user\tests\data\models\invitation\Registration;
use rhosocial\user\tests\data\User;
use rhosocial\user\tests\TestCase;
use yii\db\IntegrityException;

/**
 * Class RegistrationTest
 * @package rhosocial\user\tests\models\invitation
 * @version 1.0
 * @author vistart <i@vistart.me>
 */
class RegistrationTest extends TestCase
{
    /**
     * @var User
     */
    protected $user;

    /**
     * @var User
     */
    protected $invitee;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User(['password' => '123456']);
        $this->assertTrue($this->user->register());
    }

    protected function tearDown()
    {
        if ($this->user && !$this->user->getIsNewRecord()) {
            $this->user->deregister();
        }
        if ($this->invitee && !$this->invitee->getIsNewRecord()) {
            $this->invitee->deregister();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @group invitation
     * @group register
     */
    public function testEmpty()
    {
        $this->assertInstanceOf(User::class, $this->user);
        $this->assertEmpty($this->user->invitationRegistrations);
    }

    /**
     * @group invitation
     * @group register
     * @depends testEmpty
     */
    public function testRegister()
    {
        $this->invitee = new User(['password' => '123456']);
        $this->assertTrue($this->invitee->registerAccordingToInvitation([], [], $this->user));
        $invitationRegistrations = $this->user->getInvitationRegistrations()->all();
        $this->assertNotEmpty($invitationRegistrations);
        $this->assertCount(1, $invitationRegistrations);
        $this->assertInstanceOf(User::class, $invitationRegistrations[0]->invitee);
        $this->assertEquals((string)$invitationRegistrations[0]->invitee, (string)$this->invitee);
        $this->assertEquals(Registration::INVITATION_REGISTRATION, $invitationRegistrations[0]->content);
    }

    /**
     * @group invitation
     * @group register
     * @depends testRegister
     */
    public function testDeregister()
    {
        $this->invitee = new User(['password' => '123456']);
        $this->assertTrue($this->invitee->registerAccordingToInvitation([], [], $this->user));
        $invitationRegistrations = $this->user->getInvitationRegistrations()->all();
        $this->assertCount(1, $invitationRegistrations);

        $this->assertTrue($this->invitee->deregister());
        $this->assertCount(0, $this->user->getInvitationRegistrations()->all());
    }

    /**
     * @group invitation
     * @group register
     * @depends testRegister
     */
    public function testGetInvitees()
    {
        $this->assertNotEmpty($this->user->invitationRegistrationClass);
        $class = $this->user->invitationRegistrationClass;
        $noInit = $class::buildNoInitModel();
        $invitationRegistrations = $this->user->getInvitationRegistrations()->andWhere(["<=", $noInit->createdAtAttribute, gmdate('Y-m-d H:i:s', time()-60)])->all();
        $this->assertEmpty($invitationRegistrations);

        $invitationRegistrations = $this->user->getInvitationRegistrations()->andWhere(['<=', $noInit->createdAtAttribute, gmdate('Y-m-d H:i:s', time()+60)])->all();
        $this->assertEmpty($invitationRegistrations);

        $this->invitee = new User(['password' => '123456']);
        $this->assertTrue($this->invitee->registerAccordingToInvitation([], [], $this->user));

        $invitationRegistrations = $this->user->getInvitationRegistrations()->andWhere(["<=", $noInit->createdAtAttribute, gmdate('Y-m-d H:i:s', time()-60)])->all();
        $this->assertEmpty($invitationRegistrations, 'The registration invitation should be empty.');

        $invitationRegistrations = $this->user->getInvitationRegistrations()->andWhere(['<=', $noInit->createdAtAttribute, gmdate('Y-m-d H:i:s', time()+60)])->all();
        $this->assertNotEmpty($invitationRegistrations);
        $this->assertCount(1, $invitationRegistrations);
        $this->assertEquals((string)$this->invitee, (string)$invitationRegistrations[0]->invitee);
    }

    /**
     * @group invitation
     * @group register
     * @depends testRegister
     */
    public function testFindByInvitee()
    {
        $this->assertEmpty($this->user->invitationRegistrations);
        $this->assertInstanceOf(User::class, $this->user);
        $invitations = Registration::findByInvitee($this->user)->all();
        $this->assertCount(0, $invitations);

        $this->invitee = new User(['password' => '123456']);
        $this->assertTrue($this->invitee->registerAccordingToInvitation([], [], $this->user));
        unset($this->user->invitationRegistrations);
        $this->assertCount(1, $this->user->invitationRegistrations);

        $invitations = Registration::findByInvitee($this->invitee)->all();
        $this->assertCount(1, $invitations);

        $this->assertEquals((string)$this->user, (string)$invitations[0]->host);
        $this->assertEquals((string)$this->invitee, (string)$invitations[0]->invitee);
    }

    /**
     * @group invitation
     * @group register
     * @depends testGetInvitees
     */
    public function testGetInviteesByMethod()
    {
        $this->assertEmpty($this->user->invitationRegistrationInvitees);

        $this->invitee = new User(['password' => '123456']);
        $this->assertTrue($this->invitee->registerAccordingToInvitation([], [], $this->user));
        unset($this->user->invitationRegistrationInvitees);

        $this->assertNotEmpty($this->user->invitationRegistrationInvitees);
        $this->assertCount(1, $this->user->invitationRegistrationInvitees);
        $this->assertEquals((string)$this->invitee, (string)$this->user->invitationRegistrationInvitees[0]);
    }

    /**
     * @group invitation
     * @group register
     * @depends testRegister
     */
    public function testNotAllowRepeated()
    {
        $this->assertEmpty($this->user->getInvitationRegistrations()->all());

        $this->invitee = new User(['password' => '123456']);
        $this->assertTrue($this->invitee->registerAccordingToInvitation([], [], $this->user));
        $invitations = $this->user->getInvitationRegistrations()->all();
        $this->assertNotEmpty($invitations);

        $invitation = $this->user->createInvitationRegistration($this->invitee);
        $this->assertInstanceOf(Registration::class, $invitation);
        $this->assertEquals((string)$invitations[0]->host, (string)$invitation->host);
        $this->assertEquals((string)$invitations[0]->content, (string)$invitation->content);
        $this->assertEquals((string)$invitations[0]->invitee, (string)$invitation->invitee);

        $this->assertFalse($invitation->save(), "Registration Invitation Instance cannot be Saved.");
    }
}
