<?php

/**
 *  _   __ __ _____ _____ ___  ____  _____
 * | | / // // ___//_  _//   ||  __||_   _|
 * | |/ // /(__  )  / / / /| || |     | |
 * |___//_//____/  /_/ /_/ |_||_|     |_|
 * @link https://vistart.me/
 * @copyright Copyright (c) 2016 - 2022 vistart
 * @license https://vistart.me/license/
 */

namespace rhosocial\user\tests\user;

use rhosocial\user\tests\TestCase;
use rhosocial\user\tests\data\User;

/**
 * Description of AttributeLabelsTest
 *
 * @author vistart <i@vistart.me>
 */
class AttributeLabelsTest extends TestCase 
{
    protected $migrations = [
        \rhosocial\user\models\migrations\M170304140437CreateUserTable::class,
    ];

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->applyMigrations($this->migrations);
    }

    protected function tearDown(): void
    {
        $this->revertMigrations($this->migrations);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @group attribute
     */
    public function testGet() {
        $user = new User();
        $this->assertNotEmpty($user->attributeLabels());
    }

}
