name: User

jobs:
  test_php80_mysql8:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and Start containers
        run: docker-compose -f tests/environments/yii2-user-php80/mysql8.yml up -d --build && docker ps
      - name: Install dependencies
        run: |
          docker exec yii2-user-php80_mysql8_1 sh -c "composer install -v"
          sleep 60
      - name: Run tests
        run: docker exec yii2-user-php80_mysql8_1 phpunit
      - name: Stop containers
        if: always()
        run: docker-compose -f tests/environments/yii2-user-php80/mysql8.yml down
